### ISSUE TITLE
Calculating new High values from the extracted BitStream

### ISSUE THREAD

**Issue by adelcsc** [h3x3ncr7pt/MCILGraduation#1]
I don't know where is the problem here :
https://github.com/h3x3ncr7pt/MCILGraduation/blob/52dd7d28156c276b1f53e9172d6a7b5b37559c8d/MCILGraduation/MCILGraduationDlg.cpp#L186

and here is the RestoreLSBs() implementation 
https://github.com/h3x3ncr7pt/MCILGraduation/blob/52dd7d28156c276b1f53e9172d6a7b5b37559c8d/MCILGraduation/ThodiAlgo.cpp#L292

I embedded the BitStream and extracted it from pixels successfully (They Match each other, the original one and the embedded one) but the problem now is when i calculate the new High values and compare them with original one they don't match !, i don't know why

**Comment by trucs21** [comment]
High values  on the embedded image are of course different from those in the original ones. Only Low values are the same.  I guess u mean differences, that's it ?

**Comment by trucs21** [comment]
There's an error in line 301 High.at(i) &= 0x0; use 0xFE instead of 0x0

**Comment by adelcsc** [comment]
Thatnks @trucs21
